### ISSUE TITLE
Invalid SDP: Client initialization not supported.

### ISSUE THREAD

**Issue by smanemann** [Eyevinn/srt-whep#22]
Hey Again,

there seems to be another Issue, apart from the gstreamer dep., which is showing up after receiving http offers from the client: 

`{"v":0,"name":"srt_whep","msg":"[HTTP REQUEST - EVENT] Error encountered while processing the incoming HTTP request: Failed to process request: Invalid SDP: Client initialization not supported.\n\n","level":40,"hostname":"xxxxxxx","pid":29811,"time":"2023-06-29T12:57:38.115737688Z","target":"tracing_actix_web::middleware","line":256,"file":"/home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-actix-web-0.7.5/src/middleware.rs","http.client_ip":"45.xxxx","http.scheme":"http","request_id":"1a8dc9d7-3d02-48e4-873b-197e37916d32","otel.kind":"server","otel.name":"HTTP POST /channel","http.route":"/channel","exception.details":"Failed to process request: Invalid SDP: Client initialization not supported.\n\n","http.target":"/channel","http.flavor":"1.1","http.host":"3.78.220.112:8000","http.method":"POST","http.user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","exception.message":"Failed to process request: Invalid SDP: Client initialization not supported.","http.status_code":400,"otel.status_code":"OK"}`

I was trying to find some documentation around the `tracing-actix-web middleware` , but couldn't find any trace of issues with client initialization.

any idea? :)

**Comment by birme** [comment]
We don't support the client side init mode of WHEP.

**Comment by birme** [comment]
Our WHEP player supports both modes at the moment

**Comment by Wkkkkk** [comment]
Hi @smanemann, here is a short [summary](https://github.com/Eyevinn/srt-whep/issues/7) of the WHEP protocol and what supports we have for now.

**Comment by smanemann** [comment]
Thanks for the clarfications. Is there maybe a specific adapter for your WHEP player? I was using that with the WHEP Adapter for testing when I got the error.

**Comment by birme** [comment]
That should work out of the box. It tries with one mode first and if that fails tries the next one

**Comment by birme** [comment]
> Hi @smanemann, here is a short [summary](https://github.com/Eyevinn/srt-whep/issues/7) of the WHEP protocol and what supports we have for now.

Should we perhaps put this in a docs/whep.md in the repo @Wkkkkk ?

**Comment by Wkkkkk** [comment]
Related discussions are under docs/whep.md now.
