### ISSUE TITLE
Cannot access preview on port 8000

### ISSUE THREAD

**Issue by cosec90** [Eyevinn/srt-whep#39]
After running the docker commands, I am not able to get preview of the file at port 8000. Also the webpage dosent open on port 8000

Please refer the images attached below.

<img width="948" alt="srt-error-2" src="https://github.com/Eyevinn/srt-whep/assets/40483691/1f015698-13fa-4c84-918b-965a593f2943">

<img width="941" alt="srt-error" src="https://github.com/Eyevinn/srt-whep/assets/40483691/c3f783e7-19c6-4ebf-b0a4-206e280d5f39">

**Comment by birme** [comment]
Hi! You need to ensure that you are running in host-mode which is mainly supported on docker engine on Linux.

**Comment by cosec90** [comment]
Hi, I am running this on ubuntu 20.04. I am not sure what do you mean by host-mode, can you please elaborate?
Used below command to run in sudo

docker run --rm --network host eyevinntechnology/srt-whep \
  -i <SRT_SOURCE_IP>:<SRT_SOURCE_PORT> \
  -o 0.0.0.0:8888 \
  -p 8000 -s caller

**Comment by cosec90** [comment]
I am using this https://webrtc.player.eyevinn.technology/?type=whep player on chrome

**Comment by Wkkkkk** [comment]
Hi @cosec90, thanks for trying it out. 
It'd be great if you could share some context about the input SRT stream that you are using. For example, is it generated by FFmpeg, or which video profile it is using? 
Also, some [screenshots](https://github.com/Eyevinn/srt-whep/assets/15907534/6cac596f-3e6a-44b7-b17e-d924f6149b1e) of chrome console would be helpful.

**Comment by Wkkkkk** [comment]
Hi, I did a quick check myself on Ubuntu and it works fine.
To find out the problem, it might be a good idea to generate a testing input stream with command
```
## This requires gstreamer
gst-launch-1.0 -v videotestsrc ! clockoverlay ! video/x-raw, height=360, width=640 ! videoconvert ! \
    x264enc tune=zerolatency ! video/x-h264, profile=main ! \
    mpegtsmux ! srtsink uri="srt://127.0.0.1:1234?mode=listener" wait-for-connection=false
```

**Comment by cosec90** [comment]
Hi, sorry for the delayed response.

On following the above steps I got this error (from srt-whep container) while trying to play stream on webrtc player
<img width="946" alt="srt-whep-error1" src="https://github.com/Eyevinn/srt-whep/assets/40483691/c157c54f-c6f6-4470-80ae-8babb0664491">


Using chrome webrtc extension, I got this
<img width="947" alt="srt-whep-error2" src="https://github.com/Eyevinn/srt-whep/assets/40483691/7f47cc10-cd49-430f-8d1a-d477588ccbd7">

Can you tell me what am I doing wrong here?

**Comment by cosec90** [comment]
For creating srt stream I am using wms (nimble) panel and video resolution is 1280x720

Thanks

**Comment by Wkkkkk** [comment]
Hi, thanks for trying out.

This problem occurs quite often as the tool to generate SRT stream might be incompatible to each other. For example, stream generated by ffmpeg might fail to play with gstreamer/VLC on MacOS. A more comprehensive test can be seen [here](https://docs.google.com/spreadsheets/d/1RX_m5dgxLFSRlmgtdYLG1FYhjKK2UzjZvl3k8t4Wv_Y/edit?usp=sharing). 

We are working to address this issue at full speed. In the mean time, you are welcome to use our sample SRT stream for a quick test.

**Comment by cosec90** [comment]
Hi, thanks for your help.

I think its more of webrtc issue. As soon as I try to connect the server, the request fails with status code 400. Also I tried using your sample srt stream docker image but got the same results.

**Comment by Wkkkkk** [comment]
Kind reminder to @cosec90 that we have solved this problem. You are welcome to have another try.
