### ISSUE TITLE
Do not require SRT output forwarding

### ISSUE THREAD

**Issue by birme** [Eyevinn/srt-whep#58]
Today it is required to forward the SRT stream to a receiver. It should not have to be mandatory and you should be able to run it simply with:

```
srt-whep -i 127.0.0.1:8989 -p 8080 -s caller
```

**Comment by Wkkkkk** [comment]
`output_address` is now optional ("127.0.0.1:8888" by default). So it is possible to run it with 
```
srt-whep -i 127.0.0.1:8989 -p 8000  -s caller
```
